name: rag
channels:
  - conda-forge  # 최신 패키지 우선
  - nvidia       # GPU 관련 패키지 우선
  - pytorch      # PyTorch 관련 패키지 우선
  - defaults     # 기본 채널 마지막

dependencies:
  - python=3.9
  - pip=23.3.1
  - pytorch=2.0.0
  - faiss-gpu=1.7.4
  - pymupdf=1.23.8  # conda-forge에서 설치
  - pip:
      # 기본 패키지
      - streamlit==1.31.0
      - pydantic>=2.5.2
      
      # LangChain 관련 패키지 (버전 명시 제거)
      - langchain
      - langchain-community
      - langchain-huggingface
      - langchain-core
      - langchain-text-splitters
      - langchain-experimental
      - langchain-openai
      - langsmith
      - openai
      
      # ML/AI 패키지
      - transformers>=4.36.2
      - sentence-transformers>=2.3.1
      - llama-cpp-python>=0.2.39
      - bitsandbytes>=0.41.1
      - accelerate>=0.25.0
      - faiss-cpu>=1.7.4
      
      # 유틸리티 패키지
      - python-dotenv>=1.0.0
      - huggingface-hub>=0.19.4
      - requests>=2.31.0
      - omegaconf>=2.3.0
      - hydra-core>=1.3.0
      - tqdm>=4.65.0
      - nltk
      - beautifulsoup4
      - pypdf>=3.0.0
      - pdfminer.six>=20221105  # PDF 텍스트 추출용
      - pdf2image>=1.16.3       # PDF 이미지 변환용 (선택적)
# PyMuPDF(fitz)와 pypdf는 서로 다른 용도로 사용됨
# PyMuPDF: 고급 PDF 처리, 이미지 추출 등
# pypdf: 기본적인 PDF 읽기/쓰기
# LangChain의 PDF 로더들이 각각 다른 백엔드 사용
# PyMuPDFLoader: pymupdf 사용
# PDFPlumberLoader: pdfplumber 사용
# PyPDFLoader: pypdf 사용