app:
  project_name: "RAG Pipeline Demo"
  debug: true

paths:
  data_dir: "./data"
  index_dir: "./faiss_index"
  pdf_path: "./data/grid.pdf"

# splitter 유형 선택: "character", "recursive", "semantic"
splitter:
  type: "recursive"
  chunk_size: 300
  chunk_overlap: 30

embeddings:
  provider: "huggingface"  # huggingface 또는 openai
  model_configs:
    huggingface:
      model_id: "sentence-transformers/all-MiniLM-L6-v2"
    openai:
      model_id: "text-embedding-ada-002"

vectorstore:
  type: "faiss"           # "faiss", "chroma"
  persist_dir: "./vectorstore"

retriever:
  type: "ensemble"        # "bm25", "faiss", "ensemble"
  top_k: 2

llm:
  provider: "huggingface"
  model_configs:
    huggingface:
      model_id: "Qwen/Qwen1.5-0.5B-Chat"
      temperature: 0.3
    openai:
      model_id: "gpt-3.5-turbo"
      temperature: 0.3

prompt:
  style: "default"


crawler:
  start_url: "https://wikidocs.net/book/14314"
  max_depth: 3
  allowed_domains:
    - "wikidocs.net"
  exclude_paths:
    - "/models/"
    - "/datasets/"
    - "/spaces/"
    - "/blog/"
  max_pages: 50


#crawler 항목 예시: start_url(시작 URL), max_depth(재귀 깊이), allowed_domain(크롤 범위 제한).